version: "4.12"
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Worldwide31
      POSTGRES_DB: nest
    networks:
      - orjinuel
networks:
  orjinuel:
